[common]
version = "0.0.1"
is_debug = true
log_level = "DEBUG"
log_path = "./out.log"


[gateway]
# 如果有域名，请将这里设置为域名
# 该域名是为了gateway的dispatch功能使用，外网客户端通过dispatch服务获取指定的ip或者域名进行访问
# 如果不设置，那么客户端是通过ip访问；如果设置，那么客户端将通过该域名访问
web_domain = ""

# server_id need to be global unique,because it is used in uuid generate
# 服务器ID，每台服务器ID必须是唯一的，该id将用于生成uuid
server_id = 1

#"nats-route://user:pass@127.0.0.1:4245",
nats_addrs = [	
        "nats://10.7.14.236:4222",
        "nats://10.7.14.26:4222",    
]

[provider]
# gateway启动的协议容器，默认启动tcp
invoked = [
        "tcp",
        "websocket",
]

#  tcp provider
tcp_addr = ":8993"
#在tcp协议容器中启用tls
enable_tls = false
tls_cert = "configs/cert.pem"
tls_key = "configs/key.pem"

# websocket provider
ws_addr = ":8994"

[etcd]
addrs = [
        "10.7.24.191:2379",
        "10.7.24.192:2379",
]

# 通过该key获取stream的服务器节点信息
streams = "/gomqtt/stream/etcd/reportdir/"
# 通过该key获取gateway的节点信息
rooms = "/gomqtt/room/etcd/addrs"

[mqtt]
# 服务器允许的最大qos等级，超过则进行降级
qos_max = 1

# 默认的keepalive时间
#当客户端传来的keepalive==0时，则自动替换为默认值
default_keepalive = 60

# 最小的keepalive时间
#若客户端设置的keepalive时间小于该值，则自动校正为该值
min_keepalive = 20

# 最大keepalive时间
#若客户端设置的keepalive时间大于该值，则自动校准为该值
max_keepalive = 120

# 用户名的最大长度(字节)
max_user_len = 40
# 用户密码的最大长度(字节)
max_password_len = 40

[dispatch]
# dispatch服务监听地址
addr = ":8906"

[mutex]
#  the type of mutex login,when is mutex,only one client is allowed to connect to gateway
# 1: disable mutx login
# 2: mutex with Username
# 3: mutex with Username and  ClientID
# 4: mutex with ClientID 
type = 2